const TICKETS = 'TICKETS'
const FILTER_MORE_TICKETS = 'FILTER-MORE_TICKETS'
const SET_CHECKED_lIST = 'SET-CHECKED-lIST'
const SET_CHECK_ALL = 'SET_CHECK_ALL'
const BUTTON_FAST = 'BUTTON-FAST'
const BUTTON_SALES = 'BUTTON_SALES'
const BUTTON_OPTIMAL = 'BUTTON-OPTIMAL'
const LOADING_BEGIN = 'LOADING-BEGIN'
const LOADING_END = 'LOADING-END'
const STOP_INC = 'STOP-INC'
const STOP_STATIC = 'STOP-STATIC'
const ERROR = 'ERROR'
export {
  TICKETS,
  FILTER_MORE_TICKETS,
  SET_CHECK_ALL,
  // eslint-disable-next-line camelcase
  SET_CHECKED_lIST,
  BUTTON_SALES,
  BUTTON_FAST,
  BUTTON_OPTIMAL,
  LOADING_BEGIN,
  LOADING_END,
  STOP_STATIC,
  STOP_INC,
  ERROR,
}
